---
title: "OBIS Taxa Testing"
author: "Sebastian DiGeronimo"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tibble")
library("tidyr")
library("readr")
library("purrr")
library("dplyr")
library("stringr")
library("forcats")
library("glue")
library("fs")
library("magrittr")
```

```{r}
func <- paste0(getwd(),"/../scripts/match_taxa_fix.R")
file.name <- paste0(getwd(),"/../data/raw/TaxonMatch_RcodeTest.xlsx")

# source of new function
source(func)

# read example file
TaxonMatch_RcodeTest <- readxl::read_excel(file.name)

# select only column of scienctific names
taxa <- TaxonMatch_RcodeTest %>%
    select(scientificName)

rm(func, file.name)
```


```{r}
taxa.name <- taxa %$% 
     as.vector(scientificName) 
taxa.name 

# orignal uses
obis.taxa <- obistools::match_taxa(taxa.name , ask = T)
obis.taxa

```

```{r}
# updated use
obis.new.taxa <- match_taxa_fix(taxa.name, fuzzy = TRUE, ask = T)

obis.taxa
obis.new.taxa
```