---
title: "obis_training"
author: "Sebastian DiGeronimo"
date: "3/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readxl")
library("hablar") # might be useful when needing to fix names
library("worrms")

library("tidyverse")
library("ggplot2")
library("ggforce")
library("tibble")
library("tidyr")
library("readr")
library("purrr")
library("dplyr")
library("stringr")
library("forcats")
library("lubridate")
library("glue")
library("fs")
library("geosphere")
library("vroom")
library("plotly")
library("magrittr")

```

```{r create-dir}
# will create a set directory if does not exists
# useful for new projects
mainDir <- getwd()
subDir <-
    c("/data/raw",
      "/data/processed",
      "/data/plots",
      "/data/metadata",
      "/Rmd",
      "/scripts")

fs::dir_create(path = paste0(mainDir,"/",subDir))
rm(mainDir, subDir)
```


```{r load-taxa-data}
file.dir <- paste0(getwd(),"/../data")


file.taxa <- fs::dir_ls(path = file.dir,
           regexp = "Analysis.*\\.xlsx$")[1]


skips <-  which(readxl::read_xlsx(file.taxa, range = cell_cols("A"), col_names = FALSE )=="Taxa") - 1
taxa <- readxl::read_xlsx(file.taxa,  skip = skips,)

taxa %>% select(1:2)
taxa.name <- taxa %>% select(1)

rm(skips, file.dir, file.taxa)
```

```{r worms-test-url}
library(jsonlite) #https://cran.r-project.org/web/packages/jsonlite/
library(httr)



namesToMatch <- c("Solea soleo") #, "Abra Albo", "sdqkljflkfjqsmlfds")

#Convert the namesToMatch to a valid REST-url
urlNamesPart <- ""
for (index in 1:length(namesToMatch)) {
	urlNamesPart <- sprintf("%s&scientificnames[]=%s", urlNamesPart, namesToMatch[index]);
}


urlNamesPart <- URLencode(urlNamesPart)

#The dyanmic build of the URL causes an obsolete '&' at the beginning of the string, so remove it
urlNamesPart <- substring(urlNamesPart, 2)

#Build the final REST-url
url <- sprintf("http://www.marinespecies.org/rest/AphiaRecordsByMatchNames?%s", urlNamesPart);

#Get the actual data from the URL
matches <- fromJSON(url)

#Handle the data (each requested name has an list of results)
for (matchesindex in 1:length(namesToMatch)) {
	#Get the results for the current index
	currentResultList = matches[[matchesindex]]

	#Get the number of list entries for the first column
	numberOfResults <- length(currentResultList[[1]])

	#Handle empty data due to no matches found
	if (is.na(currentResultList[[1]][[1]])) {
		numberOfResults <- 0
	}
	print(sprintf("%d Result(s) found for %s", numberOfResults, namesToMatch[matchesindex]))
	if (numberOfResults > 0) {
		for (listentry in 1:numberOfResults) {
			print(sprintf("ID: %d, SCIENTIFICNAME: %s, MATCH_TYPE: %s",
				currentResultList[["AphiaID"]][listentry],
				currentResultList[["scientificname"]][listentry],
				currentResultList[["match_type"]][listentry]
			));
		}
	}
}
```

```{r worrms-test-lib}
library("worrms")
worrms::wm_records_name(name       = 'Coryphaena')
test <-  wm_records_taxamatch(name = 'Leucophaeus scoresbii')
test[[1]]$AphiaID
wm_name2id_(name                    = "Leucophaeus", fuzzy = TRUE)

wm_records_taxamatch(name          = "Siphonophorae", fuzzy = TRUE)
wm_records_common(name             = "Siphonophore", fuzzy = TRUE)
wm_records_common(name      = "fish", fuzzy = TRUE)



test1 <-
    taxa.name %>% separate(Taxa, c("y1", "y2"), sep = "spp.", remove = FALSE)
test1 %>%
    mutate(y2 = str_c(y2, "", "sp."))

test1 %>%
    mutate(y21 = str_replace_all(y2, "" = "sp."))

taxa.name %>% mutate(subs = str_split(Taxa, pattern = "sp")[1])


tes   <-  str_detect(taxa.name$Taxa, pattern = "sp")
tes

tax_test <-  list()
# for (i in seq(nrow(taxa.name))) {
for (i in 1:3) {
 print(taxa.name[[i,1]])
    tax_test[[taxa.name[[i, 1]]]] <- tryCatch({
        wm_records_taxamatch(as.character(taxa.name[i, 1]),
                             fuzzy = TRUE,
                             marine_only = TRUE)[1]
    }, warning = function(w) {
        message(sprintf("Warning in %s: %s", deparse(w[["call"]]), w[["message"]]))
        
    }, error = function(e) {
        message(sprintf("Error in %s: %s", deparse(e[["call"]]), e[["message"]]))
        NA_character_
    })
  
 
}
bind_rows(unlist(tax_test, recursive = FALSE))


tax_test <- wm_records_taxamatch(as.character(taxa.name[i,1]), fuzzy = TRUE, marine_only = TRUE)[[1]]
tax_test <- wm_records_taxamatch("Copepoda", fuzzy = TRUE, marine_only = TRUE)[[1]]
tax_test %>%
    select(AphiaID, scientificname) %>%
    mutate(taxa = taxa.name[[i,1]])


test <- wm_records_common("Warbler", fuzzy = TRUE)
# Black-throated Gray Warbler
wm_records_common()


t1 <- (test  %>%
    select(AphiaID)  %>%
    c())[[1]]
t1[1]

common <- list()
for (i in seq(t1)) {
    common[i] <- worrms::wm_id2name(t1[i])
    
}
com <- common %>% bind_rows()
     
?wm_common_id
```