---
title: "OBIS Taxa Testing"
author: "Sebastian DiGeronimo"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readxl")
library("obistools")
library("worrms")

```

```{r}
func <- paste0(getwd(),"/../scripts/match_taxa_fix.R")
file.name <- paste0(getwd(),"/../data/raw/TaxonMatch_RcodeTest.xlsx")

# new function for taxa matching
source(func)

# example file with scientific names
TaxonMatch_RcodeTest <- readxl::read_excel(file.name)

# select vector of scientific names
taxa.name <- TaxonMatch_RcodeTest$scientificName

rm(func, file.name)
```


```{r}
# orignal uses
obis.taxa <- obistools::match_taxa(taxa.name , ask = T)
obis.taxa
```
From the original use, the matches that did not have anything were left blank. 
Using the new function allows the correction of these without having to change
the names within the excel spreadsheet before trying again.


```{r}
# updated use
obis.new.taxa <- match_taxa_fix(taxa.name, fuzzy = TRUE, ask = T)
obis.new.taxa

```
```{r}

    
obis.taxa
obis.new.taxa

# examine the differences
cbind(taxa.name, obis.taxa[1], obis.new.taxa[1])

```


